- docs/pull_request_template.md
There won't be a database for this app, so this section isn't needed.
Removes the database schema changes section of the PR template. There won't be a database so it's not necessary. Closes #11.
None
For the last time, NO
NO
NO
> Remove database schema section from PR template

- openapi.yml
This adds a skeleton OpenAPI spec file. The response objects are mostly just placeholders until we decide on a data model. Closes DIP-111 #done.
- https://mitlibraries.atlassian.net/browse/DIP-111
NO
NO
> Add initial OpenAPI spec

- Gopkg.lock
- main.go
- parsers/marc.go
This adds one of the more widely used, lightweight cli packages. Nothing
has changed in the way it works except that a rules file can now be
passed as an option rather than being hardcoded.
The new CLI can be interacted with as follows:
```
$ go run main.go --help
$ go run main.go parse --rules fixtures/marc_rules.json < fixtures/test.mrc
```
- https://mitlibraries.atlassian.net/browse/DIP-124
NO
YES
> Add CLI package

- main.go
Changes from stdin to a supplied file path for signifying the MARC file to process.
Debugging with stdin was proving difficult at best so switching this this now rather than later will make my life somewhat easier.
- go run main.go parse -h
- go run main.go parse --rules fixtures/marc_rules.json fixtures/test.mrc
- go run main.go parse fixtures/test.mrc
- go run main.go parse - < fixtures/record1.mrc
NO
NO
> Use flag instead of stdin to supply file to process

- fixtures/marc_rules.json
- parsers/marc.go
- parsers/marc_test.go
Initial marc rules retrieval was done based on the order of the rules in the file which was not going to be sustainavble longerm. This provides a `getRule` method that allows retrieving by MARC tag string which is at least an improvement even if does not end up as our final form.
Adds handling for content_type which demonstrates our ability to pull from the leader (and then uses a lookup table to translate the byte to a text representaton.
Adds handling for the year of publication which demonstrates our ability to take a portion of a returned subfield. :see_no_evil:
Documents that our implementation of 856 is naive and not what we need to do longterm.
`go run main.go parse fixtures/record1.mrc` and see the additional data fields are now populated.
- …
> Improve marc rules retrieval and add more rules

- .gitignore
- parsers/marc.go
Creates channels and sends Records over the channel.
This allows for processing as the records are entering the system
rather than storing them all in memory before processing.
Running the 50,000 record dump we have from Aleph will now take 6MB of RAM instead of 8GB.
- https://mitlibraries.atlassian.net/browse/DIP-140
NO
NO
> Send records to channel for later consumption by es and JSON

- main.go
- marc.go
- marc_test.go
I started running into circular imports with the old project layout. One
solution is to pull marc.Process out into a new package. This should be
pulled out of marc.go eventually anyways. The other solution, which I've
done here, is to just flatten the project into a single package. This is
the easiest, most straightforward solution, and a layout many go
projects adopt.
The moves the parser package up one level into main. 
The project layout is flatter. `go build`, `go test` and `go install` can all be run from the project root now.
NO
NO
> Refactor project layout

- Gopkg.lock
- consumers.go
- main.go
- marc.go
This adds Elasticsearch bulk indexing capabilities. Things are pretty hard coded at the moment until we can refactor the pipeline. I've also stubbed out a create subcommand that will create a (hardcoded) index. We will likely want to add more functionality here in the future.
1. ```$ go build && go install```
2. Start up an Elasticsearch instance on port 9200:
```
$ docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.4.2
```
3. Create an index: `$ mario create`
4. Index things: `$ mario parse fixtures/mit_test_records.mrc`
5. Go to `http://localhost:9200/timdex/_search?q=*` in your browser.
- https://mitlibraries.atlassian.net/browse/DIP-138
YES
YES
> Add Elasticsearch bulk loader

- .gitignore
- consumers.go
- main.go
- marc.go
Adds a JSON consumer so that records can be consumed and exported as JSON instead of to Elasticsearch. Also adds a CLI flag to specify JSON output. Default is Elasticsearch consumer.
JSON output currently prints to log, but we can add additional output streams (file, etc.) as needed.
- https://mitlibraries.atlassian.net/browse/DIP-126
NO
NO
> Add JSON consumer and CLI flag for JSON output

- consumers.go
- main.go
- marc.go
Log writes to stderr, print logs to stdout.
I wanted to be able to export our json to a file and this allows that. It also tweaks the json creation slightly to create valid json by creating the array syntax and adding comma separators.
I also slipped the original consumer back in because I felt for the stage I am at in development I really just want a quick dump of information and not full data structures or es writes. I can be swayed this is not useful later... but I kinda do want this in for now if it doesn't make anyone super angry.
`go install; mario parse fixtures/mit_test_records.mrc --consumer json > yo.json`
NO
NO
> export valid json to stdout

- consumers.go
- consumers_test.go
- fixtures/marc_rules.json
- marc.go
- marc_test.go
- Completes https://mitlibraries.atlassian.net/browse/DIP-139 with some
exceptions that will be opened on individual tickets for resolving in
a future sprint.
- Adds initial Consumer testing by providing an io.Writer to the Consumer functions that we default to stdout in normal use but can override to a buffer in testing. ES consumer will require a different approach.
- https://mitlibraries.atlassian.net/browse/DIP-139
YES
NO
> Additional MARC mappings

- consumers_test.go
- jsonrecord.go
- jsonrecord_test.go
- main.go
- marc.go
- marc_test.go
- record.go
- adds support for ingesting json files created using the JSONConsumer
- moves some shared Record logic to a generic file
- creates Process interface
- adds `type` flag to cli. This defaults to marc for now as that will be our primary use case for a while still
- a couple tests use smaller data set to speed up test runs
The main.main() logic is getting really convoluted and should be addressed. I think this works adds enough general information about how we'll handle multiple data sources in the future to let us think about how we might address this. It is my opinion that should be handled in a separate PR.
```
go install; mario parse fixtures/mit_test_records.json  --consumer json --type json
```
- none; oops.
NO
NO
> Support for multiple data sources

- fixtures/marc_rules.json
This updates the `in_bibliography` rule after discussion with the metadata team. We now get matches in the test record set.
- https://mitlibraries.atlassian.net/browse/DIP-157
YES
NO
> Update in_bibliography rule

- consumers.go
- consumers_test.go
- jsonrecord.go
- jsonrecord_test.go
- main.go
- marc.go
- marc_test.go
- pipeline.go
- pipeline_test.go
This commit primarily adds a Pipeline struct that handles construction
and execution of the Pipeline, along with three interfaces. A Pipeline
consists of a single Generator, zero or more Transformers and a single
Consumer.
The main goal was to decouple the pipeline functionality from the
parsers, which is where it was living. The pipeline is now entirely
created and run by main, and none of the parsers or consumers even know
about the pipeline.
The other big change is to the pipeline itself handle hooking up
channels between stages. It's no longer necessary to create any channels
up front. The pipeline's Run() method will return an empty channel that
can be read from to determine when the pipeline has completed.
This decoupling makes the test setup considerably easier. Slotting in
new …
> Separate out pipeline functionality.

- README.md
- main.go
This removes the hardcoded values for the Elasticsearch URL and index.
They can now be specified at the CLI and will fall back to defaults if
not given.
Map a non-default port when starting the docker image:
```
$ docker run -p 9201:9200 -p 9300:9300 -e "discovery.type=single-node" \
docker.elastic.co/elasticsearch/elasticsearch:6.4.2
$ mario create --url http://127.0.0.1:9201 --index foobar
```
Then go to http://127.0.0.1:9201/foobar in your browser.
- https://mitlibraries.atlassian.net/browse/DIP-143
NO
NO
> Allow configuration of ES at runtime

- main.go
- transformers.go
- transformers_test.go
This adds a simple transformer that counts the number of records
ingested. The Counter transformer has a count attribute that can be read
after the pipeline has finished. A debug flag has been added to print
this information.
`$ mario parse -c title --debug fixtures/test.mrc`
NO
NO
> Add record counter

- consumers.go
- main.go
- marc.go
- marc_test.go
- record.go
Adds consistent elasticsearch `_id` so reindexing will overwrite a record and not add a new one.
This also adds support for the naming we expect on the API side. This isn't strictly necessary, but I think it will be helpful for debugging purposes in the future if the elasticsearch has the same fieldnames as the API responses. As such, this is part of DIP-164.
This removes `Record.URL` as we will be handling that as part of Record.Links.
This does not create index mappings which is the crux of what DIP-167 needs to do so this does not close the ticket even if at first look they appear related.
Drop your timdex index and index some stuff. The field names will now be lowercase and match our spreadsheet. Additionally, if you index the same content again at this stage you will not double the …
> Declare Record names for indexing

- marc.go
- record.go
Adds `Record.Source` and `Record.SourceLink`. The Source is primarily a debugging bit for the future. The latter is necessary to provide in the API and I was initially going to construct it as needed as part of API logic but this seems probably better overall to construct these links during ingest and leave the API as loosely coupled as we can to the actual sources.
YES
NO
> Adds Source and SourceLink

- Gopkg.lock
- Gopkg.toml
- main.go
This adds support for v4 signing of the Elasticsearch requests, which is
required for our Elasticsearch instance. A new command line flag has
been added (--v4) to enable signing. The order in which it will look for
signing credentials is:
1. In environment variables (AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY for the
key ID and AWS_SECRET_ACCESS_KEY or AWS_SECRET_KEY for the secret key).
2. From a credentials file in $HOME/.aws/credentials.
3. From an EC2 role provider.
I'm not sure how/if this last one will work. It will probably need some
tweaking once we start running on Fargate.
To avoid having to copy/paste a bunch, I've moved the url, index and v4
command line parameters to be global params.
The current release of olivere/elastic has a bug in how it generates the
timestamp for the v4 …
> Add AWS v4 signing

- config/es_record_mappings.json
- elasticsearch.go
- main.go
Most of this configuration was taken from an auto generated index. I've changed some fields to text instead of keyword that I think make sense. Others may want adjustments later. `ignore_above` value probably needs some analysis.
To ensure we always use these rules for creating an index, we check for index existance in the Parse command and create one if it doesn't exist. Otherwise, one is automatically created for us based on the Record struct in go which isn't exactly what we want here.
This also starts to move some es config to a config package as our main.go. This will likely get more work after https://mitlibraries.atlassian.net/browse/DIP-169.
Create an index and view it. One particularly difference you can note between the auto generated config and this one is the …
> Elasticsearch Record index configuration

- marc.go
- marc_test.go
Removes empty language fields from record in MARC parser.
Logs error if MARC record has no title (this is an indication of an invalid record).
Run MARC parser with JSON consumer on test record set. There will no longer be empty strings in the languages arrays.
- https://mitlibraries.atlassian.net/browse/DIP-168
YES
NO
> Deal with remaining empty fields in output from MARC records

- marc.go
What does this PR do?
Adds content_type back to our Records now that fml supports leader elements.
What are the relevant tickets?
https://mitlibraries.atlassian.net/browse/DIP-206
Requires Full Reindexing of all Sources?
YES
Includes new or updated dependencies?
NO
> Add content_type now that fml support it

- config/es_record_mappings.json
This adds a lowercase filter to all of our keyword fields.
In general capitalization shouldn't matter for keyword fields. Since the
filter is applied both by the indexer and the query parser the change
shouldn't affect anything that's currently using capitalization. It will
provide for a less frustrating experience if your capitalization is off,
though.
The easiest way to see the change will be to ingest the fixture records without this change and do a search for `content_type.keyword:"cartographic material"`. This should return no results. If you then reingest with these changes the same search should return results whose content type shows as "Cartographic material".
- https://mitlibraries.atlassian.net/browse/DIP-178
YES
NO
> Add lowercase filter to keyword fields

- Gopkg.lock
- main.go
- s3.go
Adds ability to load a file from S3 to the ingest command. Also removes option to use stdin as input, for which we don't currently have a use case.
Like the existing ES functionality, assumes AWS credentials are configured in the environment.
Ingest a marc file from S3, providing an S3 file path argument (e.g., ```mario ingest s3://my-bucket/my-object```)
- https://mitlibraries.atlassian.net/browse/DIP-211
NO
YES
> Add S3 object input loading to ingest command

- Dockerfile
- Makefile
This adds a Makefile to simplify the process of building the container
and pushing it to the ECR repo. I've also modified the Dockerfile to
shrink the size of the resulting image.
You'll need a docker version >=17.05 in order to build the container.
```
$ make dist
$ docker run --rm mario
```
You should see the mario help page. Doing anything more than this with the container would require shenanigans.
NO
NO
> Add Makefile for building container

- .travis.yml
When merging a PR onto master travis will now build the docker image and
push it to the AWS ECR staging repo.
This stage will only run when merging to master, so there's no way to review.
NO
NO
> Add deploy stage to travis build

- .travis.yml
In non-Python builds pip defaults to system-wide installation.
> Install AWS CLI to user only

- Dockerfile
Because Go for some reason won't just blindly accept whatever dodgy
certificate it encounters.
You can't really. You have to run the Fargate task to see the original error message.
NO
NO
> Add certs to docker image

- elasticsearch.go
- main.go
- previously hardcoded "aleph" value is now the default of a new flag "prefix"
- auto mode will create a new index, demote any old indexes with the supplied prefix, and promote the new index. Auto mode will not demote any indexes that have different prefixes.
- a known pattern for aleph daily update files will override auto mode (so the s3 trigger can remain the same for both modes [alternatively the lambda would have to deal with this]) and instead select the current index for the prefix supplied. If there is not one current index it stops processing and reports an error condition.
- shared es logic moved to existing `elasticsearch.go` file
- Ingest a few files
- Promote one to production
- Ingest a new file in `auto` mode. You should now see the new ingest as production and the previous …
> Support both full automatic and daily update modes

- marc.go
- marc_test.go
- translates aleph location codes to user friendly(ish) phrases
- translates aleph collection codes to user friendly(ish) phrases
I'm told these don't change often, but do change. I didn't trust that we'd always get updates in the same file format, so I just hard coded all of the logic into the application. I don't love this, but there wasn't really a better option at this time.
Process some files and check the Holdings locations and collection information.
- https://mitlibraries.atlassian.net/browse/DIP-218
YES if we want the holdings to reflect these changes... we can wait until we move to prod ES cluster though
NO
> Dip 218 location lookups

- config/es_record_mappings.json
- config/marc_rules.json
- marc.go
- record.go
Replaces 'country_of_publication' with 'place_of_publication' in the data model, because many MARC records use state or other location types that are not countries.
Reindex and view record
- https://mitlibraries.atlassian.net/browse/DIP-221
YES
NO
> Replace 'country_of_publication' with 'place_of_publication' in data model

- Makefile
The promote target should be run manually whenever you are ready to
deploy the latest staging build to production. It will copy the image
tagged `latest` from the stage registry to the prod registry.
You can't, unless you want to promote to production as part of the review.
NO
NO
> Add promote target to Makefile

- marc.go
- marc_test.go
- record.go
Removes duplicate values from fields and removes empty values from holdings field.
Reindex and look at record. Subjects field previously had a lot of duplicates and doesn't anymore, and there should be no blank values in the holdings field.
- https://mitlibraries.atlassian.net/browse/DIP-192
YES
YES | NO
> Dip 192 remove duplicate values

- config/es_record_mappings.json
- config/marc_rules.json
- marc.go
- marc_test.go
- record.go
Removes format field from record and instead includes format in holdings, since we often have multiple holdings of a single item in different formats (e.g., a print volume and an electronic resource). This decision was made with input from metadata folks who agreed that it makes the most sense. Note that "Internet resource" holdings do not list a format, since the location is already clearly defined as "Internet resource" and format would be identical to that.
Re-index and view records. Format is now part of the holdings field.
- https://mitlibraries.atlassian.net/browse/DIP-149
YES
NO
> Remove format field from record and add format to holdings

- Gopkg.lock
- Gopkg.toml
- config/es_record_mappings.json
- elasticsearch.go
- main.go
- marc.go
- updates fml and other dependencies (good luck!)
- checks for legal statuses for Leader.Status and skips records that are either deletes / suppressions or not valid (we'll come back to the deletes / suppressions later)
- adds count for errors
- adds additional worker for bulkinserts
- adds callback to bulkinserts, checks for errors, and logs them if they exist
- changes the date field in Elasticsearch to `text` instead of `date`. This is far from ideal but is a bandaid to get all of the records indexed. A new ticket has been opened to address this more usefully in the the future: https://mitlibraries.atlassian.net/browse/DIP-248
- Dates are awful + MARC is awful = fml
Pulling this branch and running a full index into Elasticsearch should now:
- actually complete now
- use text fields for …
> Leader status check, ES error checking, Dates are text now

- marc.go
- marc_test.go
Only keeps OCLC numbers for our OclcNumbers field and removes an unnecessary prefix from same.
`mario ingest --debug --consumer json fixtures/mit_test_records.mrc` on master and this branch and note the master branch has a bunch of old system numbers and the OCLC number has a prefix that this branch removes.
- https://mitlibraries.atlassian.net/browse/DIP-256
YES, ideally.
NO
> Remove old system numbers and prefix from OCLC numbers

- .gitignore
- config/es_record_mappings.json
- config/marc_rules.json
- marc.go
- marc_test.go
- record.go
Combines authors into the contributor field. Future work will provide additional "kinds" of contributors but for now a generic "author" for 1xx and "contributor" for 7xx fields is our path forward. Future work under DIP-259 has been proposed to handle the more detailed "kinds".
Ingest some records and check the contributors to see both 1xx and 7xx fields included.
- https://mitlibraries.atlassian.net/browse/DIP-257
- https://mitlibraries.atlassian.net/browse/DIP-253
YES
Additionally, TIMDEX needs to handle these changes prior to a full reindex.
NO
> Combine authors and contributors as contributors

- config/es_record_mappings.json
Our MARC records often insert specific trailing punctutation that prevent the noop of ElasticSearches keyword field from matching typical user input. This char_filter approach intends to allow better exact matches on the title fields so we can get better results in TIMDEX! (which will get a separate PR that leverages this new index).
ugh
There is an open TIMDEX! pr that uses an Elasticsearch index that this code was used to build.
- https://mitlibraries.atlassian.net/browse/DIP-794
YES
NO
> title exact_value field strips trailing punctuation

- elasticsearch.go
- main.go
This is proactive work to prevent confusion for future uses of our shared ES instance by labeling more clearly which application is using the resource rather than a generic like "production".
- https://mitlibraries.atlassian.net/browse/DIP-225
NO, but will will need to manually promote the current aleph index and then update the Heroku ENV for timdex prod and staging to use `timdex-prod` instead of `production`.
NO
> Use timdex-prod instead of production for alias

- archives.go
- archives_test.go
- config/aspace_code_mappings.yml
- go.mod
- go.sum
Makes a few changes to the archives parser and related tests. Fields update include ContentType (added to ES record), Links (updated the link "kind"), and Contributor (added the roles lookup and a better fallback).
Ingest some Aspace records and view the result. You should now see a ContentType in the full record, any links types should be Kind: Digital object, and the Contributor default for most records will be Creator (reflecting the Aspace record default).
- https://mitlibraries.atlassian.net/browse/DIP-261
Aspace only
YES
> Archives parser updates

- docs/architecture-decisions/0012-use-lambda-and-fargate-for-task-execution.md
- docs/architecture-decisions/0013-use-sqs-and-airflow-for-task-execution.md
This adds an ADR replacing the current Lambda/Fargate indexing task with
a process driven by SQS and Airflow.
> Add ADR for SQS/Airflow

- main.go
This fixes #85. The colons are just replaced with dashes in the datetime
appended to the index name. The change shouldn't affect anything with
the current pipeline.
1. Startup a local ES instance
2. `make install`
3. `mario ingest --auto fixtures/mit_test_records.mrc`
4. `mario aliases`
YES
NO
> Remove colons from index name

- elasticsearch.go
- main.go
The reindex command wouldn't be used for the normal ingest process,
but it's useful to have around when an existing index needs to be
reindexed for some reason. This is much faster than reindexing from
source.
1. Start up an ES instance
2. mario --index foo ingest fixtures/mit_test_records.mrc
3. mario --index foo reindex --destination bar
NO
NO
> Add a reindex command

- docs/architecture-decisions/0008-use-one-s3-bucket-per-source.md
- docs/architecture-decisions/0011-indexing-commands-and-flows.md
- docs/architecture-decisions/0014-structure-of-cli.md
- docs/architecture-decisions/0015-use-a-single-bucket.md
This proposes to replace a couple ADRs. The first defines the structure
of the CLI, but more in terms of guidelines than explicitly listing out
commands. As the CLI will likely continue to evolve, this ADR should
remain relevant with those changes.
The second ADR redefines our usage of S3 buckets, shifting to a single
bucket for all source data.
> Add new CLI and new bucket ADRs

- pkg/client/elastic.go
- pkg/record/record.go
This adds a new client that wraps the underlying Elasticsearch client.
The goal here is to address two existing problems. The first is that a
lot of business logic has found its way into main.go and it needs to not
live there. This moves most of the logic around indexes into this
client. The second problem is that the direct usage of the underlying
client makes it difficult to unit test parts of the application. By
encapsulating that in a trimmed down client we can more easily mock an
Elasticsearch instance.
The client also more explicitly enforces business rules for our indexing
strategy. Retrieving the current index for a particular source will
return an error if more than one index is found. Promoting a new index
is now an atomic action. These steps should prevent us from reaching a …
> Add a new Elasticsearch client

- Dockerfile
There were a few things wrong with the docker image as a result of
switching to pkger. The first is that it apparently needs underlying go
tooling on the system, so the base build for the production container
was switched to the golang alpine image. The second is mostly that I
still don't really understand how pkger works. I think the problem is
probably due to the interactions between pkger and go modules. More work
to understand what's going on here is needed, but for now copying the
config files to the final layer is a quick fix.
NO
NO
> Fix broken docker image

- cmd/mario/main.go
- pkg/generator/marc.go
- pkg/ingester/ingester.go
Adds back the logging that was removed during the application refactor last summer plus a bit of extra logging for debugging. This does not address any other issues around the refactor.
The refactor removed a few lines of logging that are valuable for checking whether Aleph updates are indexing properly. This returns them to the codebase and adds a bit of extra logging to help with debugging.
Run and promote a full Aleph ingest locally, then ingest an update file and see more information in the logging.
- https://mitlibraries.atlassian.net/browse/DISCO-204
- https://mitlibraries.atlassian.net/browse/DISCO-131
- https://mitlibraries.atlassian.net/browse/DISCO-114
NO
NO
> Replace logging that was removed

- cmd/mario/main.go
- pkg/client/elastic.go
- pkg/ingester/ingester.go
Consolidates the `type` and `prefix` flags in the cli into one flag, `source`, which is used to determine both the source data mapping to use and the index name prefix. Also makes `source` a required flag because we don't want to default to a source that may differ from the metadata file being ingested.
`mario ingest -h` will show the cli options. Attempting to run `mario ingest` without a `--source` flag will not work. To see it in action, run `mario ingest -s aleph fixtures/test.mrc`, or corollary command for other sources/source files.
NOTE: It is definitely possible to run this with mismatched source and ingest file. This will either result in no records being ingested or will throw an error, because the parser is determined by the source and will not succeed with a different type of …
> Simplify use of source/type and prefix in cli

- README.md
- cmd/mario/main.go
- pkg/client/elastic.go
- pkg/generator/marc.go
- pkg/generator/marc_test.go
- pkg/ingester/ingester.go
The CLI has been a bit messy and confusing for some time as documented in [ADR 14](https://github.com/MITLibraries/mario/blob/6982a33e1552c0e9eea1a21ba4459cfdc37b2baf/docs/architecture-decisions/0014-structure-of-cli.md). This finishes the work to bring the CLI in line with that ADR.
* Removes index from global options
* Organizes all commands in two groups: ES actions and index actions
* Adds "required" to all required options
* Reorganizes ingest options to have index first (to match the other index commands) followed by required options, then optional ones
* Removes RulesFile option from ingest command, also removes it from the ingester configuration, and instead hard codes the rules file directly in the MARC generator (to match other MARC-specific config file handling)
* Removes …
> Clean up CLI

- Makefile
Our Makefile commands were still using the AWS CLI v1 commands, which
are now deprecated. This updates it to use commands that will
work in either version.
NO
NO
> Update Makefile to use AWS CLI v2 commands

- pkg/generator/marc.go
Fixes a typo in the MARC generator that caused an index out-of-range panic for records with multiple 856 fields but a single 866 field.
NO
NO
> Fix typo in MARC generator

- .github/workflows/stage.yml
- .github/workflows/test.yml
- Dockerfile
* Dockerfile update to result in a successful build that will run a Mario command
* Github Actions config files now reference the main branch instead of master
For reasons currently unknown, updates in a previous commit caused problems with the Docker build that prevented running the Mario command in the container. CI build on merge was also broken due to previous renaming of the main branch.
`make dist` to build the docker image and then `docker run mitlibraries/mario:latest -h` to see the Mario help command
NO
NO
> Fix bug in Dockerfile

- Dockerfile
This PR adds multistage builds back to the docker container. 
The update to 1.16 broke multistage builds, as far as I can tell this is because go was expecting more verbose mod/config directives.  
These changes were based on knowledge from this post indicating mod might be the culprit.  
https://stackoverflow.com/questions/66894200/go-go-mod-file-not-found-in-current-directory-or-any-parent-directory-see-go
Pull this branch -
Run `make dist`
Run `docker run mario:latest -h`
- https://mitlibraries.atlassian.net/browse/DISCO-291
NO
NO
> Add multistage build back to 116

- pkg/generator/marc.go
Some records in the latest full Alma export are lacking 008 fields, which caused a panic in the MARC generator. This adds a check to skip and report any records missing an 008 field.
NO
NO
> Handle no 008 field error

- .github/workflows/stage.yml
- .github/workflows/test.yml
* Comments out the deploy job in stage Github Actions workflow
* Adds 2.x branch to ignore in test Github Actions workflow
* Updates Go to our current version 1.16 in both workflows
While we work on breaking changes that will result in version 3.0 of Mario, we don't want the main branch to auto-deploy to our current staging environment.
Any desired deployments from the main branch will need to be done manually from local.
We can't until it's merged.
* https://mitlibraries.atlassian.net/browse/RDI-39
NO
NO
> Disable auto-deploy from main branch

- .github/workflows/stage.yml
- .github/workflows/test.yml
While we work on breaking changes that will result in version 3.0 of Mario, we want to retain a long-running branch for version 2.x that can be deployed to production until 3.0 is ready to go live.
* Updates the staging Github actions workflow to deploy the 2.x branch
* Updates the test Github actions workflow to ignore the 2.x branch in addition to main
* Updates both workflows to use our current Go version, 1.16
I don't think we can until it's merged.
All future work intended for immediate production release should be PR'd into the 2.x branch. Work to support new features can be PR'd into the main branch.
* https://mitlibraries.atlassian.net/browse/RDI-39
NO
NO
> Update Github actions to deploy from 2.x branch

- .github/workflows/dev_ecr_push.yml
- Makefile
This PR modifies the makefile to work in dev, and adds the github action to compile and publish the container to dev on pushes to main.  
While we did decide to not *tag* images with dev, stage, or prod, we still use ECR registries with dev, stage, or prod in the name.  So i add the -dev back in a few places.  
I also added the action which will compile and publish the dev image automatically on pushes to main.  
We haven't decided how to do dev->stage->prod promotion yet, so i have left that unmodified for now.  When stage is deployed, we'll decide on that and add actions/makefile commands. 
With dev credentials, you can run `make dist-dev` and `make publish-dev` 
Unsure, Jira is still down.
NO
NO
> Actions and makefile changes for dev

- config/es_record_mappings.json
Why are these changes being introduced:
* nested objects were not searchable in an all fields search
How does this address that need:
* Adds nested objects to parent
* More info: https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html#nested-params
YES
NO
> Include nested objects in parent

- fixtures/timdex_record_samples.json
- pkg/record/record.go
In some sources, a contributor can have multiple affiliations and/or identifiers. This PR:
* Updates Contributor Affiliation and Identifier type from string to array of strings.
* Updates fixtures to reflect this change.
Try loading the fixtures into a local OpenSearch instance or our Dev1 instance and see the updated Contributor model in the records. Also works with output from the transmogrifier app.
- https://mitlibraries.atlassian.net/browse/RDI-79
NO (has already been done on Dev1)
NO
> Update Contributor model
